
GET https://i21hukkgp9.execute-api.us-east-1.amazonaws.com/prod/spaces?id=9c16ab77-3e66-4459-81a6-877ef5cd69a2

###

GET https://i21hukkgp9.execute-api.us-east-1.amazonaws.com/prod/spaces

###

POST https://i21hukkgp9.execute-api.us-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
  "location": "Rochester, MN",
  "body": "SPAM."
}

###

PUT https://i21hukkgp9.execute-api.us-east-1.amazonaws.com/prod/spaces?id=8c6178a8-b295-46cc-9122-66abaac5afc2
Content-Type: application/json

{
  "location": "Stewertville, MN",
  "body": "Bowling."
}

###

DELETE https://i21hukkgp9.execute-api.us-east-1.amazonaws.com/prod/spaces?id=a82b4c39-3d99-4500-8477-2434bb660951